# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

