# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0004_auto_20201028_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_inter',
            field=models.DateTimeField(null=True),
        ),
    ]
