# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0005_auto_20201028_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='libelle',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='lieu',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='nom_inter',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('B', 'Brouillon'), ('V', 'Valid\xe9'), ('T', 'Termin\xe9')], max_length=1, null=True),
        ),
    ]
